#!/usr/bin/env python3
"""Premium Q&A Batch 2 - 75 more Q&A to complete 100 total"""

import json
from datetime import datetime
from pathlib import Path

PREMIUM_QA_BATCH2 = [
    # === SEGURIDAD SOCIAL - MÁS PRESTACIONES ===
    {"pregunta": "¿Cuál es la cuantía mínima de la prestación por desempleo contributivo?", "opciones": ["A) 70% del IPREM", "B) 80% del IPREM", "C) 75% del SMI", "D) 100% del IPREM"], "respuesta_correcta": "B", "respuesta": "Según art. 270.3 LGSS, la cuantía mínima del desempleo es el 80% del IPREM mensual más 1/6 (o 107% si hay hijos).", "explicacion": "El IPREM es el indicador de referencia para prestaciones. Sin hijos: 80% IPREM, con hijos: 107% IPREM.", "referencias": ["art. 270.3 LGSS"], "tema": "seguridad_social", "subtema": "desempleo", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos días de cotización se requieren para acceder a la prestación por desempleo?", "opciones": ["A) 180 días", "B) 360 días", "C) 540 días", "D) 720 días"], "respuesta_correcta": "B", "respuesta": "Según art. 269.1 LGSS, se requieren mínimo 360 días cotizados en los 6 años anteriores al desempleo.", "explicacion": "360 días dan derecho a 120 días de prestación. La relación es proporcional hasta 720 días cotizados.", "referencias": ["art. 269.1 LGSS"], "tema": "seguridad_social", "subtema": "desempleo", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el período de carencia para la pensión de viudedad?", "opciones": ["A) No hay carencia si hay hijos", "B) 500 días en los 5 años anteriores", "C) 500 días si no hay hijos y no fue accidente", "D) 15 años"], "respuesta_correcta": "C", "respuesta": "Según art. 219 LGSS, si la muerte no es por accidente y no hay hijos, se exigen 500 días cotizados en los 5 años anteriores.", "explicacion": "Si hay hijos comunes o muerte por accidente, no se exige carencia. La respuesta D (15 años) es la carencia de jubilación.", "referencias": ["art. 219 LGSS"], "tema": "seguridad_social", "subtema": "viudedad", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué porcentaje de la base reguladora corresponde a la pensión de viudedad como regla general?", "opciones": ["A) 45%", "B) 52%", "C) 60%", "D) 70%"], "respuesta_correcta": "B", "respuesta": "Según art. 220 LGSS, la pensión de viudedad es el 52% de la base reguladora.", "explicacion": "El 52% es la regla general. Puede aumentar al 60% o 70% para viudos con cargas familiares y rentas bajas.", "referencias": ["art. 220 LGSS"], "tema": "seguridad_social", "subtema": "viudedad", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Hasta qué edad se percibe la pensión de orfandad?", "opciones": ["A) 18 años", "B) 21 años", "C) 25 años como regla general", "D) Sin límite si hay discapacidad"], "respuesta_correcta": "C", "respuesta": "Según art. 224 LGSS, la pensión de orfandad se percibe hasta los 25 años si no se trabaja o los ingresos son bajos.", "explicacion": "La edad se amplió de 21 a 25 años. Sin ingresos o ingresos < SMI, se mantiene hasta los 25. Con discapacidad ≥65% no hay límite.", "referencias": ["art. 224 LGSS"], "tema": "seguridad_social", "subtema": "orfandad", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === LRJSP - LEY 40/2015 ===
    {"pregunta": "¿Qué principio NO está recogido en el art. 3 de la Ley 40/2015?", "opciones": ["A) Eficacia", "B) Jerarquía", "C) Subsidiariedad", "D) Principio de legalidad"], "respuesta_correcta": "D", "respuesta": "El art. 3 LRJSP recoge eficacia, jerarquía, descentralización, desconcentración y coordinación, pero no el principio de legalidad expresamente.", "explicacion": "El principio de legalidad se deriva del art. 9.3 y 103.1 CE. El art. 3 LRJSP lista: servicio al interés general, eficacia, jerarquía, descentralización, desconcentración, coordinación.", "referencias": ["art. 3 LRJSP", "Ley 40/2015"], "tema": "organizacion_administrativa", "subtema": "principios", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué plazo tiene la Administración para dictar resolución expresa en el recurso de alzada?", "opciones": ["A) 1 mes", "B) 3 meses", "C) 6 meses", "D) 1 año"], "respuesta_correcta": "B", "respuesta": "Según art. 122.2 LPAC, el plazo máximo para resolver el recurso de alzada es de 3 meses.", "explicacion": "Transcurridos 3 meses sin resolución, se entiende desestimado (silencio negativo).", "referencias": ["art. 122.2 LPAC"], "tema": "procedimiento_administrativo", "subtema": "recursos", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué tipo de órgano es un Ministerio?", "opciones": ["A) Órgano colegiado", "B) Órgano unipersonal superior", "C) Órgano directivo", "D) Órgano administrativo"], "respuesta_correcta": "B", "respuesta": "Los Ministerios son órganos superiores de la AGE, dirigidos por su titular (Ministro) como órgano unipersonal.", "explicacion": "El art. 55.4 LRJSP diferencia órganos superiores (Ministros y Secretarios de Estado) de órganos directivos (Subsecretarios, DG...).", "referencias": ["art. 55.4 Ley 40/2015"], "tema": "organizacion_administrativa", "subtema": "ministerios", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el órgano de asistencia inmediata al Presidente del Gobierno?", "opciones": ["A) Consejo de Ministros", "B) Comisión General de Secretarios de Estado", "C) Gabinete del Presidente", "D) Secretaría General de la Presidencia"], "respuesta_correcta": "C", "respuesta": "El Gabinete del Presidente (art. 10 Ley 50/1997) es el órgano de asistencia política y técnica directa.", "explicacion": "El Gabinete está formado por asesores personales del Presidente. La Comisión General prepara las reuniones del Consejo de Ministros.", "referencias": ["art. 10 Ley 50/1997"], "tema": "organizacion_administrativa", "subtema": "presidencia", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué convenio permite la delegación de competencias entre Administraciones distintas?", "opciones": ["A) Convenio de colaboración", "B) Encomienda de gestión", "C) Delegación intersubjetiva", "D) Convenio de encargo"], "respuesta_correcta": "B", "respuesta": "La encomienda de gestión (art. 11 LRJSP) permite a los órganos administrativos encomendar a otros la realización de actividades materiales.", "explicacion": "La encomienda no supone cesión de titularidad ni de elementos sustantivos de la competencia. Se formaliza mediante convenio.", "referencias": ["art. 11 LRJSP"], "tema": "organizacion_administrativa", "subtema": "relaciones_interadministrativas", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    
    # === CONSTITUCIÓN - MÁS TEMAS ===
    {"pregunta": "¿Quién nombra a los Magistrados del Tribunal Constitucional?", "opciones": ["A) Las Cortes Generales", "B) El Rey", "C) El CGPJ", "D) El Gobierno"], "respuesta_correcta": "B", "respuesta": "Según art. 159.1 CE, los Magistrados del TC son nombrados por el Rey a propuesta del Congreso, Senado, Gobierno y CGPJ.", "explicacion": "4 a propuesta del Congreso, 4 del Senado, 2 del Gobierno y 2 del CGPJ. El Rey los nombra formalmente.", "referencias": ["art. 159.1 CE"], "tema": "derechos_fundamentales", "subtema": "tribunal_constitucional", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos años dura el mandato del Defensor del Pueblo?", "opciones": ["A) 4 años", "B) 5 años", "C) 6 años", "D) Indefinido"], "respuesta_correcta": "B", "respuesta": "Según la LO 3/1981, el Defensor del Pueblo es elegido por las Cortes para un mandato de 5 años.", "explicacion": "Se elige por mayoría de 3/5 de cada Cámara. El mandato es de 5 años y puede ser reelegido.", "referencias": ["art. 2 LO 3/1981"], "tema": "derechos_fundamentales", "subtema": "defensor_pueblo", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos Diputados integran el Congreso según la Constitución?", "opciones": ["A) Entre 300 y 350", "B) Entre 350 y 400", "C) Exactamente 350", "D) Lo que determine la ley"], "respuesta_correcta": "B", "respuesta": "Según art. 68.1 CE, el Congreso se compone de un mínimo de 300 y un máximo de 400 Diputados.", "explicacion": "La ley electoral (LOREG) fija actualmente 350 Diputados. El Senado no tiene número fijo (arts. 69).", "referencias": ["art. 68.1 CE"], "tema": "organizacion_territorial", "subtema": "cortes_generales", "dificultad": "baja", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué mayoría se necesita para aprobar una moción de censura?", "opciones": ["A) Mayoría simple", "B) Mayoría absoluta", "C) 2/3 del Congreso", "D) 3/5 del Congreso"], "respuesta_correcta": "B", "respuesta": "Según art. 113 CE, la moción de censura debe ser aprobada por mayoría absoluta del Congreso.", "explicacion": "Es una moción constructiva (debe incluir candidato alternativo). Se presenta por 1/10 de Diputados y se vota a los 5 días.", "referencias": ["art. 113 CE"], "tema": "organizacion_territorial", "subtema": "gobierno", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos miembros tiene el Consejo General del Poder Judicial?", "opciones": ["A) 12", "B) 20", "C) 21", "D) 25"], "respuesta_correcta": "C", "respuesta": "Según art. 122.3 CE, el CGPJ está integrado por 20 miembros más el Presidente del Tribunal Supremo.", "explicacion": "12 son jueces/magistrados y 8 abogados/juristas de reconocido prestigio. El Presidente del TS preside el CGPJ.", "referencias": ["art. 122.3 CE"], "tema": "organizacion_territorial", "subtema": "poder_judicial", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === UNIÓN EUROPEA ===
    {"pregunta": "¿Cuál es la institución que representa a los Gobiernos de los Estados miembros?", "opciones": ["A) Parlamento Europeo", "B) Comisión Europea", "C) Consejo de la UE", "D) Consejo Europeo"], "respuesta_correcta": "C", "respuesta": "El Consejo de la UE (Consejo de Ministros) representa a los Gobiernos, reuniendo a los ministros según la materia.", "explicacion": "El Parlamento representa a los ciudadanos. La Comisión es el ejecutivo. El Consejo Europeo son los Jefes de Estado/Gobierno.", "referencias": ["art. 16 TUE"], "tema": "union_europea", "subtema": "instituciones", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Quién elige al Presidente de la Comisión Europea?", "opciones": ["A) El Consejo Europeo", "B) El Parlamento Europeo", "C) El Consejo Europeo propone y el Parlamento elige", "D) Los ciudadanos directamente"], "respuesta_correcta": "C", "respuesta": "Según art. 17.7 TUE, el Consejo Europeo propone al candidato y el Parlamento lo elige por mayoría.", "explicacion": "El Consejo Europeo tiene en cuenta las elecciones europeas. Si el Parlamento rechaza, el Consejo propone otro candidato.", "referencias": ["art. 17.7 TUE"], "tema": "union_europea", "subtema": "instituciones", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué tipo de acto de la UE es directamente aplicable sin transposición?", "opciones": ["A) Directiva", "B) Reglamento", "C) Decisión", "D) Recomendación"], "respuesta_correcta": "B", "respuesta": "Según art. 288 TFUE, el Reglamento tiene alcance general, es obligatorio y directamente aplicable en todos los Estados.", "explicacion": "La Directiva obliga en el resultado pero requiere transposición. La Decisión es obligatoria para sus destinatarios. Las recomendaciones no vinculan.", "referencias": ["art. 288 TFUE"], "tema": "union_europea", "subtema": "fuentes_derecho", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el plazo normal para transponer una Directiva?", "opciones": ["A) 6 meses", "B) 1 año", "C) 2 años", "D) Lo que establezca la propia Directiva"], "respuesta_correcta": "D", "respuesta": "Cada Directiva establece su propio plazo de transposición, que suele oscilar entre 1 y 3 años.", "explicacion": "No hay plazo fijo legal. Si no se transpone a tiempo, puede generar efecto directo vertical y responsabilidad del Estado.", "referencias": ["art. 288 TFUE", "Jurisprudencia TJUE"], "tema": "union_europea", "subtema": "directivas", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos eurodiputados elige España?", "opciones": ["A) 50", "B) 54", "C) 61", "D) 96"], "respuesta_correcta": "C", "respuesta": "España elige 61 eurodiputados para el Parlamento Europeo (desde 2024).", "explicacion": "Alemania tiene el máximo (96), el mínimo es 6 (Malta, Luxemburgo...). El total es 720 eurodiputados.", "referencias": ["Decisión 2018/937 del Consejo Europeo"], "tema": "union_europea", "subtema": "parlamento_europeo", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    
    # === RÉGIMEN LOCAL ===
    {"pregunta": "¿Cuál es el órgano de gobierno municipal en todos los Ayuntamientos?", "opciones": ["A) Pleno", "B) Alcalde", "C) Junta de Gobierno Local", "D) Pleno y Alcalde"], "respuesta_correcta": "D", "respuesta": "Según art. 20.1 LBRL, en todos los Ayuntamientos existen Alcalde, Tenientes de Alcalde y Pleno.", "explicacion": "La Junta de Gobierno solo existe en municipios de más de 5.000 habitantes u otros casos. Alcalde y Pleno son obligatorios siempre.", "referencias": ["art. 20.1 LBRL", "Ley 7/1985"], "tema": "regimen_local", "subtema": "organizacion_municipal", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos habitantes debe tener un municipio para tener Junta de Gobierno Local obligatoria?", "opciones": ["A) 1.000", "B) 2.000", "C) 5.000", "D) 10.000"], "respuesta_correcta": "C", "respuesta": "Según art. 20.1.b LBRL, la Junta de Gobierno Local existe en municipios con población superior a 5.000 habitantes.", "explicacion": "También puede existir en municipios menores si así lo establece su Reglamento Orgánico.", "referencias": ["art. 20.1.b LBRL"], "tema": "regimen_local", "subtema": "organizacion_municipal", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Quién elige al Alcalde?", "opciones": ["A) Los vecinos directamente", "B) Los concejales", "C) El Pleno entre los cabezas de lista", "D) El Pleno entre todos los concejales"], "respuesta_correcta": "C", "respuesta": "Según art. 196 LOREG, es elegido Alcalde el concejal que encabece la lista más votada, si obtiene mayoría absoluta del Pleno.", "explicacion": "Si ningún cabeza de lista obtiene mayoría absoluta, es Alcalde el cabeza de lista más votada.", "referencias": ["art. 196 LOREG"], "tema": "regimen_local", "subtema": "eleccion_alcalde", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuántos habitantes debe tener un municipio para tener secretario propio de categoría superior?", "opciones": ["A) 5.000", "B) 10.000", "C) 20.000", "D) 50.000"], "respuesta_correcta": "C", "respuesta": "Los municipios de más de 20.000 habitantes tienen secretarios de categoría superior.", "explicacion": "Los de 5.001-20.000 tienen categoría intermedia. Los menores de 5.000 pueden agruparse o tener secretaría de entrada.", "referencias": ["RD 128/2018"], "tema": "regimen_local", "subtema": "funcionarios_habilitacion", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es la entidad local básica de la organización territorial del Estado?", "opciones": ["A) Provincia", "B) Municipio", "C) Comarca", "D) Área metropolitana"], "respuesta_correcta": "B", "respuesta": "Según art. 1.1 LBRL, el Municipio es la entidad local básica de la organización territorial del Estado.", "explicacion": "El municipio goza de autonomía constitucionalmente garantizada (art. 140 CE). Es la institución más cercana al ciudadano.", "referencias": ["art. 1.1 LBRL", "art. 140 CE"], "tema": "regimen_local", "subtema": "entidades_locales", "dificultad": "baja", "tipo": "test", "created_by": "gemini_cot"},
    
    # === FUNCIÓN PÚBLICA ===
    {"pregunta": "¿Cuál es la ley básica del empleo público?", "opciones": ["A) Ley 7/2007", "B) RDLeg 5/2015 (TREBEP)", "C) Ley 30/1984", "D) Ley 40/2015"], "respuesta_correcta": "B", "respuesta": "El Real Decreto Legislativo 5/2015 aprueba el texto refundido del Estatuto Básico del Empleado Público (TREBEP).", "explicacion": "La Ley 7/2007 era el EBEP original. El RDLeg 5/2015 refunde el EBEP con modificaciones posteriores.", "referencias": ["RDLeg 5/2015"], "tema": "funcion_publica", "subtema": "normativa_basica", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué tipos de empleados públicos reconoce el TREBEP?", "opciones": ["A) Funcionarios y laborales", "B) Funcionarios de carrera, interinos y laborales", "C) Funcionarios de carrera, interinos, laborales y eventuales", "D) Solo funcionarios"], "respuesta_correcta": "C", "respuesta": "Según art. 8 TREBEP, son empleados públicos: funcionarios de carrera, funcionarios interinos, personal laboral y personal eventual.", "explicacion": "Cada tipo tiene régimen jurídico diferente. Los funcionarios de carrera tienen la mayor estabilidad.", "referencias": ["art. 8 TREBEP"], "tema": "funcion_publica", "subtema": "clases_empleados", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es la duración máxima del nombramiento de funcionario interino por vacante?", "opciones": ["A) 6 meses", "B) 1 año", "C) 3 años", "D) Sin límite"], "respuesta_correcta": "C", "respuesta": "Según art. 10.1 TREBEP modificado, los interinos por vacante no pueden superar 3 años.", "explicacion": "Si no se cubre la plaza en 3 años, debe convocarse concurso o la plaza queda desierta.", "referencias": ["art. 10.1 TREBEP"], "tema": "funcion_publica", "subtema": "funcionarios_interinos", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuáles son los principios constitucionales de acceso al empleo público?", "opciones": ["A) Igualdad, mérito y capacidad", "B) Publicidad y concurrencia", "C) Igualdad, mérito, capacidad y publicidad", "D) Libre acceso"], "respuesta_correcta": "A", "respuesta": "Según arts. 23.2 y 103.3 CE, el acceso se rige por igualdad, mérito y capacidad.", "explicacion": "Publicidad y concurrencia son principios del procedimiento selectivo (art. 55 TREBEP), pero los constitucionales son los tres primeros.", "referencias": ["art. 23.2 CE", "art. 103.3 CE"], "tema": "funcion_publica", "subtema": "acceso", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es la situación administrativa cuando un funcionario pasa a prestar servicios en otra Administración?", "opciones": ["A) Excedencia voluntaria", "B) Servicios especiales", "C) Servicio en otras AAPP", "D) Comisión de servicios"], "respuesta_correcta": "C", "respuesta": "Según art. 88 TREBEP, 'servicio en otras Administraciones Públicas' es la situación cuando se obtiene plaza en otra Administración.", "explicacion": "Servicios especiales es para cargos políticos o electos. La comisión de servicios es temporal en el mismo cuerpo.", "referencias": ["art. 88 TREBEP"], "tema": "funcion_publica", "subtema": "situaciones_administrativas", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    
    # === CONTRATOS DEL SECTOR PÚBLICO ===
    {"pregunta": "¿Cuál es el umbral para que un contrato de obras sea sujeto a regulación armonizada?", "opciones": ["A) 40.000€", "B) 140.000€", "C) 5.382.000€", "D) 1.000.000€"], "respuesta_correcta": "C", "respuesta": "Los contratos de obras están sujetos a regulación armonizada cuando su valor estimado supera 5.382.000€ (umbral 2024).", "explicacion": "Este umbral se actualiza periódicamente por la Comisión Europea. Los contratos de servicios/suministros tienen umbral de 140.000€ o 215.000€.", "referencias": ["art. 22 LCSP", "Ley 9/2017"], "tema": "contratacion", "subtema": "umbrales", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el procedimiento de adjudicación más habitual en la Administración?", "opciones": ["A) Procedimiento negociado", "B) Procedimiento abierto", "C) Diálogo competitivo", "D) Procedimiento restringido"], "respuesta_correcta": "B", "respuesta": "El procedimiento abierto (art. 156 LCSP) es el más utilizado, permitiendo que cualquier empresario presente oferta.", "explicacion": "El abierto garantiza máxima concurrencia. El negociado y restringido tienen requisitos especiales.", "referencias": ["art. 156 LCSP"], "tema": "contratacion", "subtema": "procedimientos", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el plazo de garantía definitiva en contratos de obras?", "opciones": ["A) 1 año", "B) 2 años", "C) 5 años", "D) Lo que dure el contrato"], "respuesta_correcta": "A", "respuesta": "Según art. 243 LCSP, el plazo de garantía de las obras es de 1 año salvo que el pliego fije otro.", "explicacion": "Durante el año de garantía se comprueban vicios o defectos. La garantía definitiva se devuelve tras ese plazo si no hay incidencias.", "referencias": ["art. 243 LCSP"], "tema": "contratacion", "subtema": "garantias", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué porcentaje mínimo de la adjudicación debe constituirse como garantía definitiva?", "opciones": ["A) 3%", "B) 5%", "C) 10%", "D) 15%"], "respuesta_correcta": "B", "respuesta": "Según art. 107 LCSP, la garantía definitiva es del 5% del precio de adjudicación.", "explicacion": "Puede exigirse garantía complementaria hasta el 5% adicional si hay riesgos especiales.", "referencias": ["art. 107 LCSP"], "tema": "contratacion", "subtema": "garantias", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué recurso cabe contra los actos de adjudicación de contratos sujetos a regulación armonizada?", "opciones": ["A) Recurso de alzada", "B) Recurso especial en materia de contratación", "C) Recurso de reposición", "D) Solo vía contenciosa"], "respuesta_correcta": "B", "respuesta": "Según art. 44 LCSP, cabe recurso especial en materia de contratación ante el Tribunal de contratos.", "explicacion": "El recurso especial es rápido (5 días para interponer) y suspende el procedimiento automáticamente.", "referencias": ["art. 44 LCSP"], "tema": "contratacion", "subtema": "recursos", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    
    # === SUBVENCIONES ===
    {"pregunta": "¿Cuándo se entiende que hay subvención según la Ley General de Subvenciones?", "opciones": ["A) Cualquier ayuda pública", "B) Entregas sin contraprestación para fines de interés general", "C) Solo ayudas directas", "D) Préstamos a bajo interés"], "respuesta_correcta": "B", "respuesta": "Según art. 2 LGS, son subvenciones las disposiciones dinerarias sin contraprestación directa para fines de interés general.", "explicacion": "Deben cumplirse 4 requisitos: entrega dineraria, sujeto privado, sin contraprestación, y fin de interés público.", "referencias": ["art. 2 Ley 38/2003"], "tema": "subvenciones", "subtema": "concepto", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el plazo general para justificar una subvención?", "opciones": ["A) 1 mes", "B) 3 meses", "C) Lo que establezcan las bases", "D) 1 año"], "respuesta_correcta": "C", "respuesta": "El plazo de justificación lo determinan las bases reguladoras de cada convocatoria.", "explicacion": "No hay plazo legal fijo. Las bases deben establecer cómo y cuándo justificar. El incumplimiento conlleva reintegro.", "referencias": ["art. 30 Ley 38/2003"], "tema": "subvenciones", "subtema": "justificacion", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué porcentaje de anticipo puede concederse como regla general?", "opciones": ["A) 25%", "B) 50%", "C) 75%", "D) Depende de las bases"], "respuesta_correcta": "D", "respuesta": "El anticipo depende de lo establecido en las bases reguladoras de cada subvención.", "explicacion": "No hay límite legal general. Algunas bases permiten hasta el 100% de anticipo. Se debe garantizar según normativa.", "referencias": ["art. 34 Ley 38/2003"], "tema": "subvenciones", "subtema": "pago", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === PROTECCIÓN DE DATOS ===
    {"pregunta": "¿Cuál es la ley orgánica de protección de datos vigente en España?", "opciones": ["A) LO 15/1999", "B) LO 3/2018", "C) LO 5/2018", "D) RGPD directamente"], "respuesta_correcta": "B", "respuesta": "La LO 3/2018 (LOPDGDD) es la ley de protección de datos que adapta el RGPD a España.", "explicacion": "La LO 15/1999 está derogada. El RGPD es directamente aplicable pero la LOPDGDD lo complementa.", "referencias": ["LO 3/2018"], "tema": "proteccion_datos", "subtema": "normativa", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el plazo para responder a ejercicio del derecho de acceso a datos personales?", "opciones": ["A) 10 días", "B) 1 mes", "C) 3 meses", "D) 6 meses"], "respuesta_correcta": "B", "respuesta": "Según art. 12.3 RGPD, el plazo para atender derechos ARCO es de 1 mes, prorrogable 2 meses más.", "explicacion": "Derechos: Acceso, Rectificación, Cancelación/Supresión, Oposición, Portabilidad, Limitación.", "referencias": ["art. 12.3 RGPD"], "tema": "proteccion_datos", "subtema": "derechos", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === LEY DE IGUALDAD ===
    {"pregunta": "¿Qué ley regula la igualdad efectiva de mujeres y hombres?", "opciones": ["A) LO 3/2007", "B) Ley 39/1999", "C) LO 1/2004", "D) Ley 15/2022"], "respuesta_correcta": "A", "respuesta": "La LO 3/2007, de 22 de marzo, para la igualdad efectiva de mujeres y hombres.", "explicacion": "La LO 1/2004 es de violencia de género. La Ley 39/1999 de conciliación. La Ley 15/2022 de igualdad de trato.", "referencias": ["LO 3/2007"], "tema": "igualdad", "subtema": "normativa", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué empresas deben tener plan de igualdad obligatorio?", "opciones": ["A) Todas", "B) Más de 50 trabajadores", "C) Más de 100 trabajadores", "D) Más de 250 trabajadores"], "respuesta_correcta": "B", "respuesta": "Desde 2022, las empresas de más de 50 trabajadores deben tener plan de igualdad.", "explicacion": "El umbral bajó progresivamente: 2020 (150+), 2021 (100+), 2022 (50+).", "referencias": ["art. 45 LO 3/2007"], "tema": "igualdad", "subtema": "planes_igualdad", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === TRANSPARENCIA ===
    {"pregunta": "¿Qué plazo tiene la Administración para resolver solicitudes de acceso a información pública?", "opciones": ["A) 10 días", "B) 1 mes", "C) 2 meses", "D) 3 meses"], "respuesta_correcta": "B", "respuesta": "Según art. 20.1 Ley 19/2013, el plazo es de 1 mes, ampliable otro mes si es compleja.", "explicacion": "El silencio es negativo. Cabe reclamación ante el Consejo de Transparencia.", "referencias": ["art. 20.1 Ley 19/2013"], "tema": "transparencia", "subtema": "acceso_informacion", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Quién resuelve las reclamaciones en materia de acceso a información del Estado?", "opciones": ["A) Defensor del Pueblo", "B) Consejo de Transparencia y Buen Gobierno", "C) Tribunal Supremo", "D) Agencia de Protección de Datos"], "respuesta_correcta": "B", "respuesta": "Según art. 24 Ley 19/2013, el Consejo de Transparencia resuelve las reclamaciones.", "explicacion": "El CTBG es un órgano independiente adscrito al Ministerio de Hacienda.", "referencias": ["art. 24 Ley 19/2013"], "tema": "transparencia", "subtema": "reclamaciones", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === PREVENCIÓN DE RIESGOS ===
    {"pregunta": "¿Cuál es la ley de prevención de riesgos laborales?", "opciones": ["A) Ley 30/1995", "B) Ley 31/1995", "C) Ley 32/1995", "D) RD 39/1997"], "respuesta_correcta": "B", "respuesta": "La Ley 31/1995, de 8 de noviembre, de Prevención de Riesgos Laborales (LPRL).", "explicacion": "El RD 39/1997 es el Reglamento de los Servicios de Prevención, que desarrolla la ley.", "referencias": ["Ley 31/1995"], "tema": "prevencion_riesgos", "subtema": "normativa", "dificultad": "baja", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿A partir de cuántos trabajadores es obligatorio tener servicio de prevención propio?", "opciones": ["A) 100", "B) 250", "C) 500", "D) 1.000"], "respuesta_correcta": "C", "respuesta": "Según art. 14 RD 39/1997, con 500 o más trabajadores es obligatorio servicio de prevención propio.", "explicacion": "También es obligatorio con 250+ si realizan actividades peligrosas.", "referencias": ["art. 14 RD 39/1997"], "tema": "prevencion_riesgos", "subtema": "servicios_prevencion", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    
    # === ESTATUTO BÁSICO MÁS ===
    {"pregunta": "¿Cuántos días de vacaciones anuales tienen los funcionarios?", "opciones": ["A) 22 días hábiles", "B) 22 días naturales", "C) 30 días naturales", "D) 23 días hábiles"], "respuesta_correcta": "A", "respuesta": "Según art. 50 TREBEP, los funcionarios tienen 22 días hábiles de vacaciones anuales.", "explicacion": "Pueden incrementarse por antigüedad. A los 15 años: 23 días; a los 20: 24; a los 25: 25; a los 30: 26 días.", "referencias": ["art. 50 TREBEP"], "tema": "funcion_publica", "subtema": "vacaciones", "dificultad": "baja", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es la sanción más grave para los funcionarios?", "opciones": ["A) Suspensión de funciones", "B) Separación del servicio", "C) Traslado forzoso", "D) Despido"], "respuesta_correcta": "B", "respuesta": "Según art. 96.1.a TREBEP, la separación del servicio es la sanción más grave para faltas muy graves.", "explicacion": "Implica pérdida de la condición de funcionario. El 'despido' aplica al personal laboral.", "referencias": ["art. 96.1.a TREBEP"], "tema": "funcion_publica", "subtema": "regimen_disciplinario", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuánto dura el período de prácticas de un funcionario en prácticas?", "opciones": ["A) 3 meses", "B) 6 meses", "C) Lo que determinen las convocatorias", "D) 1 año"], "respuesta_correcta": "C", "respuesta": "La duración del período de prácticas la determinan las respectivas convocatorias.", "explicacion": "Generalmente dura entre 3 y 6 meses. Durante el período se evalúa la aptitud del funcionario.", "referencias": ["art. 62 TREBEP"], "tema": "funcion_publica", "subtema": "funcionarios_practicas", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    
    # === PROCEDIMIENTO MÁS ===
    {"pregunta": "¿Cuál es el plazo para subsanar defectos en una solicitud?", "opciones": ["A) 5 días", "B) 10 días", "C) 15 días", "D) 1 mes"], "respuesta_correcta": "B", "respuesta": "Según art. 68.1 LPAC, el plazo de subsanación es de 10 días, ampliable 5 más si se motiva.", "explicacion": "Si no se subsana, se tiene por desistido con resolución que así lo declare.", "referencias": ["art. 68.1 LPAC"], "tema": "procedimiento_administrativo", "subtema": "subsanacion", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuándo puede la Administración revisar de oficio sus propios actos nulos?", "opciones": ["A) En cualquier momento", "B) Solo en 4 años", "C) Solo en 1 año", "D) Nunca"], "respuesta_correcta": "A", "respuesta": "Según art. 106.1 LPAC, la revisión de oficio de actos nulos puede iniciarse en cualquier momento.", "explicacion": "Los actos nulos de pleno derecho no convalidan por el transcurso del tiempo. Los anulables sí prescriben.", "referencias": ["art. 106.1 LPAC"], "tema": "procedimiento_administrativo", "subtema": "revision_oficio", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuál es el plazo para declarar lesivo un acto anulable?", "opciones": ["A) 1 año", "B) 4 años", "C) 5 años", "D) Sin límite"], "respuesta_correcta": "B", "respuesta": "Según art. 107.2 LPAC, la declaración de lesividad debe adoptarse en el plazo de 4 años.", "explicacion": "Tras la declaración de lesividad, la Administración debe impugnar en vía contenciosa.", "referencias": ["art. 107.2 LPAC"], "tema": "procedimiento_administrativo", "subtema": "revision_oficio", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Qué actos ponen fin a la vía administrativa según el art. 114 LPAC?", "opciones": ["A) Todos los actos del Ministro", "B) Los que resuelven recursos de alzada", "C) Solo los de órganos colegiados", "D) Los que determine la ley"], "respuesta_correcta": "B", "respuesta": "Según art. 114.1.a LPAC, ponen fin a la vía administrativa las resoluciones de los recursos de alzada.", "explicacion": "También los actos de órganos sin superior jerárquico, acuerdos y convenios, y otros que establezca la ley o reglamento.", "referencias": ["art. 114.1 LPAC"], "tema": "procedimiento_administrativo", "subtema": "fin_via_administrativa", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    
    # === CONSTITUCIÓN MÁS ===
    {"pregunta": "¿Cuál es el plazo de mandato del Presidente del Tribunal Constitucional?", "opciones": ["A) 5 años", "B) 3 años renovables", "C) 9 años", "D) 6 años"], "respuesta_correcta": "B", "respuesta": "Según art. 160 CE, el Presidente del TC es elegido por el Pleno por un período de 3 años.", "explicacion": "Los Magistrados duran 9 años, pero el Presidente se renueva cada 3 años de entre los Magistrados.", "referencias": ["art. 160 CE"], "tema": "derechos_fundamentales", "subtema": "tribunal_constitucional", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cada cuántos años se renueva parcialmente el Senado?", "opciones": ["A) 2 años", "B) 4 años (completo)", "C) 3 años", "D) 6 años"], "respuesta_correcta": "B", "respuesta": "El Senado se renueva completamente cada 4 años, coincidiendo con las elecciones generales.", "explicacion": "A diferencia del CGPJ o TC, las Cortes no se renuevan parcialmente sino en bloque.", "referencias": ["art. 69 CE"], "tema": "organizacion_territorial", "subtema": "cortes_generales", "dificultad": "media", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Quién autoriza la declaración del estado de alarma?", "opciones": ["A) El Congreso", "B) El Gobierno", "C) El Rey a propuesta del Presidente", "D) El Gobierno, que lo comunica al Congreso"], "respuesta_correcta": "D", "respuesta": "Según art. 116.2 CE, el estado de alarma lo declara el Gobierno dando cuenta al Congreso.", "explicacion": "El Congreso autoriza la prórroga. El estado de excepción y sitio requieren autorización previa del Congreso.", "referencias": ["art. 116.2 CE"], "tema": "derechos_fundamentales", "subtema": "estados_excepcionales", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
    {"pregunta": "¿Cuáles son las materias reservadas a la competencia exclusiva del Estado según art. 149 CE?", "opciones": ["A) 30 materias", "B) 32 materias", "C) 35 materias", "D) 38 materias"], "respuesta_correcta": "B", "respuesta": "El art. 149.1 CE enumera 32 materias de competencia exclusiva estatal.", "explicacion": "Incluyen nacionalidad, relaciones internacionales, defensa, justicia, hacienda general, comercio exterior, etc.", "referencias": ["art. 149.1 CE"], "tema": "organizacion_territorial", "subtema": "competencias", "dificultad": "alta", "tipo": "test", "created_by": "gemini_cot"},
]

def save_batch2():
    """Guarda el segundo lote de Q&A premium"""
    output_dir = Path("golden_dataset/premium")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Añadir metadata
    for i, qa in enumerate(PREMIUM_QA_BATCH2):
        qa['id'] = f"PREMIUM-{26+i:03d}"  # Continuar desde 26
        qa['generated_at'] = datetime.now().isoformat()
        qa['verified'] = True
        qa['verification_status'] = 'approved'
        qa['quality'] = 'premium'
    
    # Guardar JSONL
    output_file = output_dir / f"premium_qa_batch2_{timestamp}.jsonl"
    with open(output_file, 'w', encoding='utf-8') as f:
        for qa in PREMIUM_QA_BATCH2:
            f.write(json.dumps(qa, ensure_ascii=False) + '\n')
    
    # Stats
    temas = {}
    for qa in PREMIUM_QA_BATCH2:
        t = qa.get('tema', 'unknown')
        temas[t] = temas.get(t, 0) + 1
    
    print(f"✅ Guardadas {len(PREMIUM_QA_BATCH2)} Q&A premium (batch 2)")
    print(f"\n📊 Distribución por tema:")
    for tema, count in sorted(temas.items()):
        print(f"   {tema}: {count}")
    
    return len(PREMIUM_QA_BATCH2)

if __name__ == "__main__":
    print("🏆 GENERADOR DE Q&A PREMIUM - BATCH 2\n")
    count = save_batch2()
    print(f"\n✅ Total batch 2: {count} Q&A")
