server {
  listen 80;
  server_name electroyhogarpelotazo.tienda;
  client_max_body_size 50m;

  location / {
    proxy_pass http://127.0.0.1:8001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_connect_timeout 120s;
    proxy_send_timeout 900s;
    proxy_read_timeout 900s;
    send_timeout 900s;
    
    proxy_request_buffering on;
    proxy_buffering off;
    chunked_transfer_encoding on;
    gzip off;
  }
}

server {
  listen 443 ssl;
  http2 on;
  server_name electroyhogarpelotazo.tienda;
  client_max_body_size 50m;

  ssl_certificate     /etc/letsencrypt/live/electroyhogarpelotazo.tienda/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/electroyhogarpelotazo.tienda/privkey.pem;
  ssl_session_timeout 1d;
  ssl_protocols TLSv1.2 TLSv1.3;

  location / {
    proxy_pass http://127.0.0.1:8001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_connect_timeout 120s;
    proxy_send_timeout 900s;
    proxy_read_timeout 900s;
    send_timeout 900s;
    
    proxy_request_buffering on;
    proxy_buffering off;
    chunked_transfer_encoding on;
    gzip off;
  }

  location /explain/stream {
    proxy_pass http://127.0.0.1:8001/explain/stream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_connect_timeout 120s;
    proxy_send_timeout 900s;
    proxy_read_timeout 900s;
    send_timeout 900s;
    
    proxy_request_buffering on;
    proxy_buffering off;
    chunked_transfer_encoding on;
    gzip off;
    add_header Cache-Control no-cache;
    add_header X-Accel-Buffering no;
  }

  location /v1/ {
    proxy_pass http://127.0.0.1:8080/v1/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_connect_timeout 120s;
    proxy_send_timeout 900s;
    proxy_read_timeout 900s;
    send_timeout 900s;
    
    proxy_request_buffering on;
    proxy_buffering off;
    chunked_transfer_encoding on;
    gzip off;
  }
}
