with open("verification_agents.py", "r") as f:
    lines = f.readlines()

# Buscar línea "        ratio_con_ref = preguntas_con_ref / len(preguntas) if preguntas else 0"
start_idx = -1
for i, line in enumerate(lines):
    if "ratio_con_ref = preguntas_con_ref" in line:
        start_idx = i - 1
        break

if start_idx != -1:
    lines = lines[:start_idx] + [
        "            # Chequea si la pregunta menciona al menos a un personaje\n",
        "            if any(nombre in texto_q for nombre in nombres):\n",
        "                preguntas_conectadas += 1\n",
        "                \n",
        "        ratio = preguntas_conectadas / len(preguntas)\n",
        "        detalles[\"preguntas_conectadas\"] = preguntas_conectadas\n",
        "        detalles[\"total_preguntas\"] = len(preguntas)\n",
        "        \n",
        "        if ratio >= 0.8:\n",
        "            feedback.append(f\"✅ {ratio:.0%} de preguntas referencian al enunciado (Alta interdependencia)\")\n",
        "        elif ratio >= 0.5:\n",
        "            feedback.append(f\"⚠️ {ratio:.0%} de preguntas referencian al enunciado (Interdependencia media)\")\n",
        "        else:\n",
        "            feedback.append(f\"❌ {ratio:.0%} de preguntas referencian al enunciado (Baja interdependencia)\")\n",
        "            \n",
        "        return self._crear_resultado(ratio, feedback, detalles)\n",
        "\n",
        "# ============================================================================\n",
        "# AGENT 8: TRAP DISTRACTOR - Evalúa la calidad de las opciones incorrectas\n",
        "# ============================================================================\n",
        "\n",
        "class Agent8_TrapDistractorValidator(VerificationAgent):\n",
        "    \"\"\"Verifica: ¿Los distractores son plausibles tipológicamente?\"\"\"\n",
        "    \n",
        "    def __init__(self):\n",
        "        super().__init__(\"agent_8\", \"Trap Distractor (Opciones)\")\n",
        "        \n",
        "    def verify(self, caso: Dict[str, Any]) -> VerificationResult:\n",
        "        feedback = []\n",
        "        detalles = {}\n",
        "        \n",
        "        preguntas = caso.get(\"preguntas\", [])\n",
        "        if not preguntas:\n",
        "            return self._crear_resultado(1.0, [\"⚠️ Sin preguntas - saltando\"])\n",
        "            \n",
        "        preguntas_plausibles = 0\n",
        "        \n",
        "        for q in preguntas:\n",
        "            correcta = str(q.get(\"respuesta_correcta\", \"\")).lower()\n",
        "            distractores = [str(d).lower() for d in q.get(\"distractores\", [])]\n",
        "            \n",
        "            if not distractores:\n",
        "                continue\n",
        "                \n",
        "            tiene_numeros = bool(re.search(r'\\d+', correcta))\n",
        "            tiene_porcentajes = \"%\" in correcta\n",
        "            \n",
        "            distractores_homogeneos = 0\n",
        "            for d in distractores:\n",
        "                d_tiene_num = bool(re.search(r'\\d+', d))\n",
        "                d_tiene_pct = \"%\" in d\n",
        "                if (tiene_numeros == d_tiene_num) and (tiene_porcentajes == d_tiene_pct):\n",
        "                    distractores_homogeneos += 1\n",
        "                    \n",
        "            if distractores_homogeneos >= len(distractores) / 2:\n",
        "                preguntas_plausibles += 1\n",
        "                \n",
        "        ratio = preguntas_plausibles / len(preguntas)\n",
        "        detalles[\"preguntas_plausibles\"] = preguntas_plausibles\n",
        "        \n",
        "        if ratio >= 0.8:\n",
        "            feedback.append(f\"✅ Distractores plausibles ({ratio:.0%})\")\n",
        "        else:\n",
        "            feedback.append(f\"⚠️ Distractores de plausibilidad baja ({ratio:.0%})\")\n",
        "            \n",
        "        return self._crear_resultado(ratio, feedback, detalles)\n",
        "\n",
        "# ============================================================================\n",
        "# ORQUESTADOR DE VERIFICADORES (V14 Unificado)\n",
        "# ============================================================================\n",
        "\n",
        "class VerificationOrchestrator:\n",
        "    \"\"\"Ejecuta los agentes V14 y consolida resultados\"\"\"\n",
        "    \n",
        "    def __init__(self):\n",
        "        self.agentes = [\n",
        "            Agent1_BOEVerifier(),\n",
        "            Agent2_LegalReasoner(),\n",
        "            Agent3_Calculator(),\n",
        "            Agent4_Coherence(),\n",
        "            Agent5_TrapPedagogy(),\n",
        "            Agent7_InterdependenciaValidator(),\n",
        "            Agent8_TrapDistractorValidator()\n",
        "        ]\n",
        "    \n",
        "    def verify_caso_completo(self, caso: Dict[str, Any], verbose: bool = True) -> Dict[str, Any]:\n",
        "        resultados = {}\n",
        "        scores = []\n",
        "        \n",
        "        for agente in self.agentes:\n",
        "            try:\n",
        "                resultado = agente.verify(caso)\n",
        "                resultados[agente.agent_id] = resultado.to_dict()\n",
        "                scores.append(resultado.score)\n",
        "                \n",
        "                if verbose:\n",
        "                    status_icon = \"✅\" if resultado.status == \"PASS\" else (\"⚠️\" if resultado.score >= 0.5 else \"❌\")\n",
        "                    logger.info(f\"{status_icon} {resultado.agent_name}: {resultado.score:.0%}\")\n",
        "                    for fb in resultado.feedback[:2]:\n",
        "                        logger.info(f\"   {fb}\")\n",
        "            except Exception as e:\n",
        "                logger.error(f\"Error en {agente.agent_name}: {e}\")\n",
        "                scores.append(0.0)\n",
        "        \n",
        "        score_promedio = sum(scores) / len(scores) if scores else 0.0\n",
        "        todos_pasaron = all(s >= 0.70 for s in scores)\n",
        "        \n",
        "        return {\n",
        "            \"resultados_agentes\": resultados,\n",
        "            \"score_promedio\": score_promedio,\n",
        "            \"todos_pasaron\": todos_pasaron,\n",
        "            \"status\": \"APROBADO\" if todos_pasaron else \"PENDIENTE_REVISION\",\n",
        "            \"scores_individuales\": {ag.agent_id: s for ag, s in zip(self.agentes, scores)},\n",
        "        }\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    print(\"Módulo verification_agents.py V14 refactorizado OK\")\n"
    ]

with open("verification_agents.py", "w") as f:
    f.writelines(lines)

